packages:
  - apps/*
  - packages/*

catalog:
  "@ai-sdk/openai": ^4.0.11
  "@ai-sdk/openai-compatible": ^3.0.7
  "@aws-sdk/client-s3": ^3.1085.0
  "@openauthjs/openauth": ^0.4.3
  "@orpc/client": ^1.14.7
  "@orpc/server": ^1.14.7
  "@orpc/tanstack-query": ^1.14.7
  "@polar-sh/sdk": ^0.48.1
  "@t3-oss/env-core": ^0.13.11
  "@tailwindcss/postcss": ^4.3.2
  "@tailwindcss/vite": ^4.3.2
  "@tanstack/react-form": ^1.33.1
  "@tanstack/react-query": ^5.101.2
  "@tanstack/react-router": ^1.170.17
  "@tanstack/router-cli": ^1.167.21
  "@tanstack/react-start": ^1.168.27
  "@types/node": ^26.1.1
  "@types/pg": ^8.20.0
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  "@unpic/react": ^1.0.2
  "@vitejs/plugin-react": ^6.0.3
  "@yopem/typescript-config": ^0.2.1
  ai: ^7.0.22
  babel-plugin-react-compiler: ^1.0.0
  dayjs: ^1.11.21
  dotenv-cli: 11.0.0
  drizzle-kit: ^0.31.10
  drizzle-orm: ^0.45.2
  drizzle-zod: ^0.8.3
  ioredis: ^5.11.1
  lucide-react: ^1.24.0
  nanoid: ^6.0.0
  next-themes: ^0.4.6
  oxlint-tailwindcss: ^1.3.4
  pg: ^8.22.0
  postcss: ^8.5.18
  react-dom: ^19.2.7
  react: ^19.2.7
  server-only: ^0.0.1
  shimmer-from-structure: 2.4.5
  srvx: ^0.11.22
  tailwindcss: ^4.3.2
  transliteration: ^2.6.1
  tsdown: ^0.22.5
  typescript: ^7.0.2
  vite-plus: ^0.2.5
  vite: npm:@voidzero-dev/vite-plus-core@0.2.5
  zod: ^4.4.3

patchedDependencies:
  "@tanstack/start-plugin-core@1.171.19": patches/@tanstack__start-plugin-core@1.171.19.patch
