packages:
  - apps/*
  - packages/*
catalog:
  "@types/node": ^22.13.10
  "@yopem/try-catch": ^0.0.2
  better-auth: ^1.2.7
  dotenv-cli: ^8.0.0
  zod: ^3.24.2
catalogs:
  react:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.4
    "@types/react-dom": ^19.1.5
  tailwindcss:
    "@tailwindcss/postcss": ^4.1.6
    tailwindcss: ^4.1.6
    tw-animate-css: ^1.2.9
  config:
    "@yopem/eslint-config": ^0.1.15
    "@yopem/prettier-config": ^0.1.4
    "@yopem/typescript-config": ^0.1.0
    eslint: ^9.26.0
    prettier: ^3.5.3
    typescript: ^5.8.3
  trpc:
    "@trpc/client": ^11.1.2
    "@trpc/server": ^11.1.2
    "@trpc/tanstack-react-query": ^11.1.2
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
