import { defineConfig } from "vite-plus"

export default defineConfig({
  staged: {
    "*": "vp check --fix --no-error-on-unmatched-pattern",
    "*.{ts,tsx}": "vp lint --fix --no-error-on-unmatched-pattern",
    "*.{js,ts,tsx,json,md,yaml,yml,css}": "vp fmt --write --no-error-on-unmatched-pattern",
  },
  fmt: {
    bracketSpacing: true,
    jsxSingleQuote: false,
    printWidth: 80,
    proseWrap: "always",
    semi: false,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    experimentalTailwindcss: {
      functions: ["cn", "cva", "clsx"],
    },
    experimentalSortPackageJson: true,
    ignorePatterns: [
      "**/node_modules",
      "**/pnpm-lock.yaml",
      "**/.pnp",
      "**/.pnp.js",
      "**/.env",
      "**/.env.local",
      "**/.env.development.local",
      "**/.env.test.local",
      "**/.env.production.local",
      "**/coverage",
      "**/.turbo",
      "**/.vercel",
      "**/.next/",
      "**/out/",
      "**/build",
      "**/dist",
      "**/npm-debug.log*",
      "**/yarn-debug.log*",
      "**/yarn-error.log*",
      "**/.DS_Store",
      "**/*.pem",
      "**/tsconfig.tsbuildinfo",
      "**/*.tsbuildinfo",
      "**/AGENTS.md",
      "**/migrations/",
      "**/*.config.*",
      "**/*.patch",
      "**/routeTree.gen.ts",
    ],
    sortImports: {
      newlinesBetween: true,
      customGroups: [
        {
          groupName: "value-workspace",
          elementNamePattern: [
            "ui",
            "ui/**",
            "auth",
            "auth/**",
            "db",
            "db/**",
            "env",
            "env/**",
            "logger",
            "logger/**",
            "rpc",
            "rpc/**",
            "shared",
            "shared/**",
            "cache",
            "cache/**",
            "llm",
            "llm/**",
            "payments",
            "payments/**",
            "storage",
            "storage/**",
          ],
        },
        {
          groupName: "type-workspace",
          elementNamePattern: [
            "ui",
            "ui/**",
            "auth",
            "auth/**",
            "db",
            "db/**",
            "env",
            "env/**",
            "logger",
            "logger/**",
            "rpc",
            "rpc/**",
            "shared",
            "shared/**",
            "cache",
            "cache/**",
            "llm",
            "llm/**",
            "payments",
            "payments/**",
            "storage",
            "storage/**",
          ],
        },
      ],
      groups: [
        "type-import",
        ["value-builtin", "value-external"],
        "type-workspace",
        "value-workspace",
        "type-internal",
        "value-internal",
        ["type-parent", "type-sibling", "type-index"],
        ["value-parent", "value-sibling", "value-index"],
        "unknown",
      ],
    },
  },
  lint: {
    plugins: ["eslint", "import", "oxc", "promise", "typescript", "unicorn"],
    categories: {
      correctness: "error",
    },
    env: {
      builtin: true,
    },
    rules: {
      "import/no-relative-parent-imports": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": "error",
      "no-console": ["error", { allow: ["error", "warn", "info"] }],
      "no-constant-binary-expression": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-delete-var": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-function": "error",
      "no-empty-pattern": "error",
      "no-empty-static-block": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-global-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-expressions": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-useless-backreference": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-var": "error",
      "prefer-const": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "require-await": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "typescript/adjacent-overload-signatures": "error",
      "typescript/array-type": "error",
      "typescript/await-thenable": "error",
      "typescript/ban-tslint-comment": "error",
      "typescript/consistent-generic-constructors": "error",
      "typescript/consistent-indexed-object-style": "error",
      "typescript/consistent-type-definitions": "error",
      "typescript/consistent-type-imports": ["warn", { prefer: "type-imports", fixStyle: "separate-type-imports" }],
      "typescript/no-array-delete": "error",
      "typescript/no-base-to-string": "error",
      "typescript/no-confusing-non-null-assertion": "error",
      "typescript/no-duplicate-enum-values": "error",
      "typescript/no-duplicate-type-constituents": "error",
      "typescript/no-empty-object-type": "error",
      "typescript/no-explicit-any": "error",
      "typescript/no-extra-non-null-assertion": "error",
      "typescript/no-for-in-array": "error",
      "typescript/no-implied-eval": "error",
      "typescript/no-inferrable-types": "error",
      "typescript/no-misused-new": "error",
      "typescript/no-misused-promises": ["error", { checksVoidReturn: { attributes: false } }],
      "typescript/no-namespace": "error",
      "typescript/no-non-null-asserted-optional-chain": "error",
      "typescript/no-redundant-type-constituents": "error",
      "typescript/no-require-imports": "error",
      "typescript/no-this-alias": "error",
      "typescript/no-unnecessary-type-assertion": "error",
      "typescript/no-unnecessary-type-constraint": "error",
      "typescript/no-unsafe-declaration-merging": "error",
      "typescript/no-unsafe-enum-comparison": "error",
      "typescript/no-unsafe-function-type": "error",
      "typescript/no-unsafe-unary-minus": "error",
      "typescript/no-wrapper-object-types": "error",
      "typescript/non-nullable-type-assertion-style": "error",
      "typescript/prefer-as-const": "error",
      "typescript/prefer-for-of": "error",
      "typescript/prefer-function-type": "error",
      "typescript/prefer-includes": "error",
      "typescript/prefer-namespace-keyword": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-optional-chain": "error",
      "typescript/prefer-promise-reject-errors": "error",
      "typescript/require-await": "error",
      "typescript/restrict-plus-operands": "error",
      "typescript/triple-slash-reference": "error",
    },
    ignorePatterns: [
      "**/node_modules",
      "**/pnpm-lock.yaml",
      "**/.pnp",
      "**/.pnp.js",
      "**/.env",
      "**/.env.local",
      "**/.env.development.local",
      "**/.env.test.local",
      "**/.env.production.local",
      "**/coverage",
      "**/.turbo",
      "**/.vercel",
      "**/.next/",
      "**/out/",
      "**/build",
      "**/dist",
      "**/npm-debug.log*",
      "**/yarn-debug.log*",
      "**/yarn-error.log*",
      "**/.DS_Store",
      "**/*.pem",
      "**/tsconfig.tsbuildinfo",
      "**/*.tsbuildinfo",
      "**/next-env.d.ts",
      "**/AGENTS.md",
      "**/migrations/",
      "**/*.patch",
      "**/*.config.*",
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
})
